version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    # H2는 인메모리 DB라서 별도의 서비스가 필요가 없다
    # 환경변수 H2 Database
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_H2_CONSOLE_ENABLED: "true"
      SPRING_H2_CONSOLE_PATH: "/h2-console"
